### ISSUE TITLE
希望加入芭芭农场施肥，前几次施肥领取丰收礼包功能

### ISSUE THREAD

**Issue by Liujishou** [WYC-2020/Voltx#10]
就是前几次施肥，每施肥几次就能领100肥料礼包，希望可以加入！

**Comment by WYC-2020** [comment]
我看有领取丰收礼包的吗 100，是每次都有一百？我明天手动试试看

**Comment by Liujishou** [comment]
> 我看有领取丰收礼包的吗 100，是每次都有一百？我明天手动试试看

是前12次左右吧，不过是分开的，施肥 前3次领一次，再4次领一次，再5次领一次

**Comment by Iparuochen** [comment]
有下载地址吗
