### ISSUE TITLE
支付宝 V10.5.509500版本无法使用

### ISSUE THREAD

**Issue by shusongLu** [WYC-2020/Voltx#13]
![image](https://github.com/WYC-2020/Voltx/assets/26265884/1c3ad704-3e88-4bc8-b19e-08ed59950865)
这个版本会导致一直是小号模式,顺便大佬可以让我加一下交流群吗

**Comment by WYC-2020** [comment]
适配过，本计划放到公共目录，测试了卸载了在安装不能读取，所以放弃，目前是直接改SDK即可
