### ISSUE TITLE
跪求增加 福利金签到和收取

### ISSUE THREAD

**Issue by pjh5134** [WYC-2020/Voltx#2]
网商银行的福利金可以当钱花，水晶和蜡笔小新都有的。

**Comment by WYC-2020** [comment]
已加等我测试

**Comment by WYC-2020** [comment]
已加

**Comment by Norman45** [comment]
芝麻粒做了这个功能，但是就只能做任务(做了的任务还要在任务界面手工去收取下金币)和收取建筑实时产生的金币，没做好友功能，但是就好友功能收金币多，支付宝自带的找金币能收取前十人的金币，希望参考芝麻粒或者支付宝自带的一键收完善加上收取好友金币功能。这玩意可以直接兑换成钱，用网商银行支付时抵扣，目前一次是一块二，可以兑五次的样子，不同人不一样

**Comment by WYC-2020** [comment]
> 芝麻粒做了这个功能，但是就只能做任务(做了的任务还要在任务界面手工去收取下金币)和收取建筑实时产生的金币，没做好友功能，但是就好友功能收金币多，支付宝自带的找金币能收取前十人的金币，希望参考芝麻粒或者支付宝自带的一键收完善加上收取好友金币功能。这玩意可以直接兑换成钱，用网商银行支付时抵扣，目前一次是一块二，可以兑五次的样子，不同人不一样

什么玩意你说的是绿色经营吧

**Comment by Norman45** [comment]
> > 芝麻粒做了这个功能，但是就只能做任务(做了的任务还要在任务界面手工去收取下金币)和收取建筑实时产生的金币，没做好友功能，但是就好友功能收金币多，支付宝自带的找金币能收取前十人的金币，希望参考芝麻粒或者支付宝自带的一键收完善加上收取好友金币功能。这玩意可以直接兑换成钱，用网商银行支付时抵扣，目前一次是一块二，可以兑五次的样子，不同人不一样
> 
> 什么玩意你说的是绿色经营吧

是的呢，审题没审好，以为是一个东西了

**Comment by WYC-2020** [comment]
已加
