### ISSUE TITLE
希望加上积分兑换猜涨跌翻倍卡功能

### ISSUE THREAD

**Issue by Norman45** [WYC-2020/Voltx#6]
猜涨跌翻倍卡凌晨就被秒空了，白天根本兑换不到，只能熬夜去抢，希望加一个功能0点后积分能兑换翻倍卡。没有翻倍卡，玩猜涨跌就很难有积分奖励的，这个是获取蚂蚁积分比较好的途径。

**Comment by WYC-2020** [comment]
什么玩意说清楚具体在哪个位置

**Comment by Norman45** [comment]
> 什么玩意说清楚具体在哪个位置
蚂蚁会员积分兑换那里搜索翻倍卡
![Screenshot_20231104_140341_com eg android AlipayGphone](https://github.com/WYC-2020/Voltx/assets/31527054/18cde3d7-c2f0-490b-b6d5-82095159f24e)

**Comment by P3R5T7U9** [comment]
> 猜涨跌翻倍卡凌晨就被秒空了，白天根本兑换不到，只能熬夜去抢，希望加一个功能0点后积分能兑换翻倍卡。没有翻倍卡，玩猜涨跌就很难有积分奖励的，这个是获取蚂蚁积分比较好的途径。

来晚辽，时隔四天，挖下；

今天我才在某安上了解到“Voltx”这个xp模块，出于溯源目的，继而在Github上也刚刚搜到作者为“Voltx”这个模块所创的问题反馈仓库，继而也才看到老哥你之前开的这条Issue；

主要我最初在某安一直没翻到有酷友分享“Voltx”这个模块包，所以才来Github寻找，想着作者可能将这个模块开源在这边，没想到还真让我搜到这个模块的问题反馈仓库，但在此仓库中仍未找到成品，不知老哥你之前在哪获取“WYC”大佬开发的这个模块安装包？？

翻了之前已关闭的几个Issue，看一两位网友提到“WYC”大有创建交流群，在群内有分享这个模块安装包，如果老哥你之前已加“WYC”大创建的交流群，麻烦回复甩下交流群地址或贴下交流群的加群二维码图片，极其想进内部群获取这个模块的安装包，我到现在还没找到这个模块的安装包，跪求老哥你回复并指路下内部群地址，带我上车呗😭
