### ISSUE TITLE
求更新网商银行福利金领取

### ISSUE THREAD

**Issue by 244276041** [WYC-2020/Voltx#7]
网商银行福利金领取
赚福利金任务
这两个希望大佬添加

**Comment by WYC-2020** [comment]
已加

**Comment by 244276041** [comment]
版本哪里下载呀？？？？群里没有上传呀

**Comment by P3R5T7U9** [comment]
> 版本哪里下载呀？？？？群里没有上传呀

今天才在某安看几个酷友发的帖有分享“voltx”这款近期新出的蚂蚁森林xp模块，出于溯源目的，才在Github上搜到“voltx”这个xp模块的问题反馈仓库，继而才翻到老哥你前两天开的这条Issue；

看老哥你这条回复，感觉老哥你之前就加过“voltx”模块的官方交流群，我到现在还没找到官方交流群地址，麻烦老哥回复甩下官方交流群地址(或贴上交流群的加群二维码图片也行)，极其想加入官方交流群，球老哥回复带我上车惹😭
