### ISSUE TITLE
网商银行 福利里面的福利金

### ISSUE THREAD

**Issue by 244276041** [WYC-2020/Voltx#8]
网商银行 福利里面的福利金领取
和赚福利金任务（福利金可以直接抵扣钱！特别是还信用卡！抵扣100元呢）
求大佬添加

**Comment by WYC-2020** [comment]
不是加了嘛

**Comment by P3R5T7U9** [comment]
> 网商银行 福利里面的福利金领取 和赚福利金任务（福利金可以直接抵扣钱！特别是还信用卡！抵扣100元呢） 求大佬添加

哥啊，等你回复我之前在 #7 这条Issue里向你发提问过去三天多了，麻烦尽快回复下呗
