### ISSUE TITLE
蚂蚁森林（看神奇物种）

### ISSUE THREAD

**Issue by 244276041** [WYC-2020/Voltx#9]
麻烦大佬更新一下，大佬辛苦

**Comment by P3R5T7U9** [comment]
> 麻烦大佬更新一下，大佬辛苦

哥啊，等你回复我之前在 #7 这条Issue里向你发提问过去三天多了，还没见回复，难道WYC大当初在内部群里说过群不能在这边公开分享？？
![](https://i.ibb.co/jz88S1k/IMG-20231111-153507.jpg)

还是老哥你一直没注意到我当初在 #7 这条Issue底下向老哥你发的提问，麻烦老哥尽快回复指个路呗😭

**Comment by WYC-2020** [comment]
491120530
